// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spbasecgi.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class RSBaseReq;
@class RSBaseResp;
@class RSContact;
@class RSFaceBuffer;
@class RSGroup;
@class RSProfile;
@class RSSyncItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - RSSpbasecgiRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface RSSpbasecgiRoot : GPBRootObject
@end

#pragma mark - RSLoginReq

typedef GPB_ENUM(RSLoginReq_FieldNumber) {
  RSLoginReq_FieldNumber_BaseReq = 1,
  RSLoginReq_FieldNumber_Code = 2,
};

@interface RSLoginReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, copy, null_resettable) NSString *code;
/** Test to see if @c code has been set. */
@property(nonatomic, readwrite) BOOL hasCode;

@end

#pragma mark - RSLoginResp

typedef GPB_ENUM(RSLoginResp_FieldNumber) {
  RSLoginResp_FieldNumber_BaseResp = 1,
  RSLoginResp_FieldNumber_OpCode = 2,
  RSLoginResp_FieldNumber_UserName = 3,
  RSLoginResp_FieldNumber_SessionKey = 4,
  RSLoginResp_FieldNumber_QiniuToken = 5,
  RSLoginResp_FieldNumber_Profile = 6,
  RSLoginResp_FieldNumber_Uin = 7,
};

@interface RSLoginResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

/** enLoginOpCode */
@property(nonatomic, readwrite) uint32_t opCode;

@property(nonatomic, readwrite) BOOL hasOpCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

@property(nonatomic, readwrite, copy, null_resettable) NSData *sessionKey;
/** Test to see if @c sessionKey has been set. */
@property(nonatomic, readwrite) BOOL hasSessionKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *qiniuToken;
/** Test to see if @c qiniuToken has been set. */
@property(nonatomic, readwrite) BOOL hasQiniuToken;

@property(nonatomic, readwrite, strong, null_resettable) RSProfile *profile;
/** Test to see if @c profile has been set. */
@property(nonatomic, readwrite) BOOL hasProfile;

/** tmp */
@property(nonatomic, readwrite) uint64_t uin;

@property(nonatomic, readwrite) BOOL hasUin;
@end

#pragma mark - RSRegisterFaceReq

typedef GPB_ENUM(RSRegisterFaceReq_FieldNumber) {
  RSRegisterFaceReq_FieldNumber_BaseReq = 1,
  RSRegisterFaceReq_FieldNumber_FaceBufferListArray = 2,
};

@interface RSRegisterFaceReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSFaceBuffer*> *faceBufferListArray;
/** The number of items in @c faceBufferListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger faceBufferListArray_Count;

@end

#pragma mark - RSRegisterFaceResp

typedef GPB_ENUM(RSRegisterFaceResp_FieldNumber) {
  RSRegisterFaceResp_FieldNumber_BaseResp = 1,
};

@interface RSRegisterFaceResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@end

#pragma mark - RSSyncReq

typedef GPB_ENUM(RSSyncReq_FieldNumber) {
  RSSyncReq_FieldNumber_BaseReq = 1,
  RSSyncReq_FieldNumber_SyncBuff = 2,
  RSSyncReq_FieldNumber_Selector = 3,
};

@interface RSSyncReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, copy, null_resettable) NSData *syncBuff;
/** Test to see if @c syncBuff has been set. */
@property(nonatomic, readwrite) BOOL hasSyncBuff;

@property(nonatomic, readwrite) uint32_t selector;

@property(nonatomic, readwrite) BOOL hasSelector;
@end

#pragma mark - RSSyncItem

typedef GPB_ENUM(RSSyncItem_FieldNumber) {
  RSSyncItem_FieldNumber_Type = 1,
  RSSyncItem_FieldNumber_Seq = 2,
};

@interface RSSyncItem : GPBMessage

/** enSyncType */
@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite) uint64_t seq;

@property(nonatomic, readwrite) BOOL hasSeq;
@end

#pragma mark - RSSyncBuff

typedef GPB_ENUM(RSSyncBuff_FieldNumber) {
  RSSyncBuff_FieldNumber_ListArray = 1,
};

@interface RSSyncBuff : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSSyncItem*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - RSSyncResp

typedef GPB_ENUM(RSSyncResp_FieldNumber) {
  RSSyncResp_FieldNumber_BaseResp = 1,
  RSSyncResp_FieldNumber_SyncBuff = 2,
  RSSyncResp_FieldNumber_IsEnd = 3,
  RSSyncResp_FieldNumber_ContactListArray = 4,
  RSSyncResp_FieldNumber_GroupListArray = 5,
};

@interface RSSyncResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, copy, null_resettable) NSData *syncBuff;
/** Test to see if @c syncBuff has been set. */
@property(nonatomic, readwrite) BOOL hasSyncBuff;

@property(nonatomic, readwrite) uint32_t isEnd;

@property(nonatomic, readwrite) BOOL hasIsEnd;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSContact*> *contactListArray;
/** The number of items in @c contactListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger contactListArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSGroup*> *groupListArray;
/** The number of items in @c groupListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupListArray_Count;

@end

#pragma mark - RSAddFriendReq

typedef GPB_ENUM(RSAddFriendReq_FieldNumber) {
  RSAddFriendReq_FieldNumber_BaseReq = 1,
  RSAddFriendReq_FieldNumber_Imgurl = 2,
};

@interface RSAddFriendReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imgurl;
/** Test to see if @c imgurl has been set. */
@property(nonatomic, readwrite) BOOL hasImgurl;

@end

#pragma mark - RSAddFriendResp

typedef GPB_ENUM(RSAddFriendResp_FieldNumber) {
  RSAddFriendResp_FieldNumber_BaseResp = 1,
  RSAddFriendResp_FieldNumber_OpCode = 2,
  RSAddFriendResp_FieldNumber_ToAddArray = 3,
};

@interface RSAddFriendResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

/** enAddFriendOpCode */
@property(nonatomic, readwrite) uint32_t opCode;

@property(nonatomic, readwrite) BOOL hasOpCode;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSContact*> *toAddArray;
/** The number of items in @c toAddArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger toAddArray_Count;

@end

#pragma mark - RSGetAllContactReq

typedef GPB_ENUM(RSGetAllContactReq_FieldNumber) {
  RSGetAllContactReq_FieldNumber_BaseReq = 1,
};

@interface RSGetAllContactReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@end

#pragma mark - RSGetAllContactResp

typedef GPB_ENUM(RSGetAllContactResp_FieldNumber) {
  RSGetAllContactResp_FieldNumber_BaseResp = 1,
  RSGetAllContactResp_FieldNumber_ContactArray = 2,
};

@interface RSGetAllContactResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSContact*> *contactArray;
/** The number of items in @c contactArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger contactArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
