// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spbasecgi.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Spbasecgi.pbobjc.h"
 #import "Spcgicomm.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - RSSpbasecgiRoot

@implementation RSSpbasecgiRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - RSSpbasecgiRoot_FileDescriptor

static GPBFileDescriptor *RSSpbasecgiRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"spcgi"
                                                 objcPrefix:@"RS"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - RSLoginReq

@implementation RSLoginReq

@dynamic hasBaseReq, baseReq;
@dynamic hasCode, code;

typedef struct RSLoginReq__storage_ {
  uint32_t _has_storage_[1];
  RSBaseReq *baseReq;
  NSString *code;
} RSLoginReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseReq",
        .dataTypeSpecific.className = GPBStringifySymbol(RSBaseReq),
        .number = RSLoginReq_FieldNumber_BaseReq,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RSLoginReq__storage_, baseReq),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "code",
        .dataTypeSpecific.className = NULL,
        .number = RSLoginReq_FieldNumber_Code,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RSLoginReq__storage_, code),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RSLoginReq class]
                                     rootClass:[RSSpbasecgiRoot class]
                                          file:RSSpbasecgiRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RSLoginReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001G\000\002D\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RSLoginResp

@implementation RSLoginResp

@dynamic hasBaseResp, baseResp;
@dynamic hasOpCode, opCode;
@dynamic hasUserName, userName;
@dynamic hasSessionKey, sessionKey;
@dynamic hasQiniuToken, qiniuToken;
@dynamic hasProfile, profile;
@dynamic hasUin, uin;

typedef struct RSLoginResp__storage_ {
  uint32_t _has_storage_[1];
  uint32_t opCode;
  RSBaseResp *baseResp;
  NSString *userName;
  NSData *sessionKey;
  NSString *qiniuToken;
  RSProfile *profile;
  uint64_t uin;
} RSLoginResp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseResp",
        .dataTypeSpecific.className = GPBStringifySymbol(RSBaseResp),
        .number = RSLoginResp_FieldNumber_BaseResp,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RSLoginResp__storage_, baseResp),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "opCode",
        .dataTypeSpecific.className = NULL,
        .number = RSLoginResp_FieldNumber_OpCode,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RSLoginResp__storage_, opCode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "userName",
        .dataTypeSpecific.className = NULL,
        .number = RSLoginResp_FieldNumber_UserName,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(RSLoginResp__storage_, userName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sessionKey",
        .dataTypeSpecific.className = NULL,
        .number = RSLoginResp_FieldNumber_SessionKey,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(RSLoginResp__storage_, sessionKey),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "qiniuToken",
        .dataTypeSpecific.className = NULL,
        .number = RSLoginResp_FieldNumber_QiniuToken,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(RSLoginResp__storage_, qiniuToken),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "profile",
        .dataTypeSpecific.className = GPBStringifySymbol(RSProfile),
        .number = RSLoginResp_FieldNumber_Profile,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(RSLoginResp__storage_, profile),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "uin",
        .dataTypeSpecific.className = NULL,
        .number = RSLoginResp_FieldNumber_Uin,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(RSLoginResp__storage_, uin),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RSLoginResp class]
                                     rootClass:[RSSpbasecgiRoot class]
                                          file:RSSpbasecgiRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RSLoginResp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\007\001H\000\002F\000\003H\000\004J\000\005J\000\006G\000\007C\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RSRegisterFaceReq

@implementation RSRegisterFaceReq

@dynamic hasBaseReq, baseReq;
@dynamic faceBufferListArray, faceBufferListArray_Count;

typedef struct RSRegisterFaceReq__storage_ {
  uint32_t _has_storage_[1];
  RSBaseReq *baseReq;
  NSMutableArray *faceBufferListArray;
} RSRegisterFaceReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseReq",
        .dataTypeSpecific.className = GPBStringifySymbol(RSBaseReq),
        .number = RSRegisterFaceReq_FieldNumber_BaseReq,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RSRegisterFaceReq__storage_, baseReq),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "faceBufferListArray",
        .dataTypeSpecific.className = GPBStringifySymbol(RSFaceBuffer),
        .number = RSRegisterFaceReq_FieldNumber_FaceBufferListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(RSRegisterFaceReq__storage_, faceBufferListArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RSRegisterFaceReq class]
                                     rootClass:[RSSpbasecgiRoot class]
                                          file:RSSpbasecgiRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RSRegisterFaceReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001G\000\002\000FaceBufferList\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RSRegisterFaceResp

@implementation RSRegisterFaceResp

@dynamic hasBaseResp, baseResp;

typedef struct RSRegisterFaceResp__storage_ {
  uint32_t _has_storage_[1];
  RSBaseResp *baseResp;
} RSRegisterFaceResp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseResp",
        .dataTypeSpecific.className = GPBStringifySymbol(RSBaseResp),
        .number = RSRegisterFaceResp_FieldNumber_BaseResp,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RSRegisterFaceResp__storage_, baseResp),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RSRegisterFaceResp class]
                                     rootClass:[RSSpbasecgiRoot class]
                                          file:RSSpbasecgiRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RSRegisterFaceResp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001H\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RSSyncReq

@implementation RSSyncReq

@dynamic hasBaseReq, baseReq;
@dynamic hasSyncBuff, syncBuff;
@dynamic hasSelector, selector;

typedef struct RSSyncReq__storage_ {
  uint32_t _has_storage_[1];
  uint32_t selector;
  RSBaseReq *baseReq;
  NSData *syncBuff;
} RSSyncReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseReq",
        .dataTypeSpecific.className = GPBStringifySymbol(RSBaseReq),
        .number = RSSyncReq_FieldNumber_BaseReq,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RSSyncReq__storage_, baseReq),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "syncBuff",
        .dataTypeSpecific.className = NULL,
        .number = RSSyncReq_FieldNumber_SyncBuff,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RSSyncReq__storage_, syncBuff),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "selector",
        .dataTypeSpecific.className = NULL,
        .number = RSSyncReq_FieldNumber_Selector,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(RSSyncReq__storage_, selector),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RSSyncReq class]
                                     rootClass:[RSSpbasecgiRoot class]
                                          file:RSSpbasecgiRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RSSyncReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001G\000\002H\000\003H\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RSSyncItem

@implementation RSSyncItem

@dynamic hasType, type;
@dynamic hasSeq, seq;

typedef struct RSSyncItem__storage_ {
  uint32_t _has_storage_[1];
  uint32_t type;
  uint64_t seq;
} RSSyncItem__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = RSSyncItem_FieldNumber_Type,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RSSyncItem__storage_, type),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "seq",
        .dataTypeSpecific.className = NULL,
        .number = RSSyncItem_FieldNumber_Seq,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RSSyncItem__storage_, seq),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RSSyncItem class]
                                     rootClass:[RSSpbasecgiRoot class]
                                          file:RSSpbasecgiRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RSSyncItem__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001D\000\002C\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RSSyncBuff

@implementation RSSyncBuff

@dynamic listArray, listArray_Count;

typedef struct RSSyncBuff__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *listArray;
} RSSyncBuff__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "listArray",
        .dataTypeSpecific.className = GPBStringifySymbol(RSSyncItem),
        .number = RSSyncBuff_FieldNumber_ListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(RSSyncBuff__storage_, listArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RSSyncBuff class]
                                     rootClass:[RSSpbasecgiRoot class]
                                          file:RSSpbasecgiRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RSSyncBuff__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\000List\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RSSyncResp

@implementation RSSyncResp

@dynamic hasBaseResp, baseResp;
@dynamic hasSyncBuff, syncBuff;
@dynamic hasIsEnd, isEnd;
@dynamic contactListArray, contactListArray_Count;
@dynamic groupListArray, groupListArray_Count;

typedef struct RSSyncResp__storage_ {
  uint32_t _has_storage_[1];
  uint32_t isEnd;
  RSBaseResp *baseResp;
  NSData *syncBuff;
  NSMutableArray *contactListArray;
  NSMutableArray *groupListArray;
} RSSyncResp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseResp",
        .dataTypeSpecific.className = GPBStringifySymbol(RSBaseResp),
        .number = RSSyncResp_FieldNumber_BaseResp,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RSSyncResp__storage_, baseResp),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "syncBuff",
        .dataTypeSpecific.className = NULL,
        .number = RSSyncResp_FieldNumber_SyncBuff,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RSSyncResp__storage_, syncBuff),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "isEnd",
        .dataTypeSpecific.className = NULL,
        .number = RSSyncResp_FieldNumber_IsEnd,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(RSSyncResp__storage_, isEnd),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "contactListArray",
        .dataTypeSpecific.className = GPBStringifySymbol(RSContact),
        .number = RSSyncResp_FieldNumber_ContactListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(RSSyncResp__storage_, contactListArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "groupListArray",
        .dataTypeSpecific.className = GPBStringifySymbol(RSGroup),
        .number = RSSyncResp_FieldNumber_GroupListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(RSSyncResp__storage_, groupListArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RSSyncResp class]
                                     rootClass:[RSSpbasecgiRoot class]
                                          file:RSSpbasecgiRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RSSyncResp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\005\001H\000\002H\000\003E\000\004\000ContactList\000\005\000GroupList\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RSAddFriendReq

@implementation RSAddFriendReq

@dynamic hasBaseReq, baseReq;
@dynamic hasImgurl, imgurl;

typedef struct RSAddFriendReq__storage_ {
  uint32_t _has_storage_[1];
  RSBaseReq *baseReq;
  NSString *imgurl;
} RSAddFriendReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseReq",
        .dataTypeSpecific.className = GPBStringifySymbol(RSBaseReq),
        .number = RSAddFriendReq_FieldNumber_BaseReq,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RSAddFriendReq__storage_, baseReq),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "imgurl",
        .dataTypeSpecific.className = NULL,
        .number = RSAddFriendReq_FieldNumber_Imgurl,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RSAddFriendReq__storage_, imgurl),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RSAddFriendReq class]
                                     rootClass:[RSSpbasecgiRoot class]
                                          file:RSSpbasecgiRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RSAddFriendReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001G\000\002F\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RSAddFriendResp

@implementation RSAddFriendResp

@dynamic hasBaseResp, baseResp;
@dynamic hasOpCode, opCode;
@dynamic toAddArray, toAddArray_Count;

typedef struct RSAddFriendResp__storage_ {
  uint32_t _has_storage_[1];
  uint32_t opCode;
  RSBaseResp *baseResp;
  NSMutableArray *toAddArray;
} RSAddFriendResp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseResp",
        .dataTypeSpecific.className = GPBStringifySymbol(RSBaseResp),
        .number = RSAddFriendResp_FieldNumber_BaseResp,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RSAddFriendResp__storage_, baseResp),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "opCode",
        .dataTypeSpecific.className = NULL,
        .number = RSAddFriendResp_FieldNumber_OpCode,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RSAddFriendResp__storage_, opCode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "toAddArray",
        .dataTypeSpecific.className = GPBStringifySymbol(RSContact),
        .number = RSAddFriendResp_FieldNumber_ToAddArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(RSAddFriendResp__storage_, toAddArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RSAddFriendResp class]
                                     rootClass:[RSSpbasecgiRoot class]
                                          file:RSSpbasecgiRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RSAddFriendResp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001H\000\002F\000\003\000ToAdd\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RSGetAllContactReq

@implementation RSGetAllContactReq

@dynamic hasBaseReq, baseReq;

typedef struct RSGetAllContactReq__storage_ {
  uint32_t _has_storage_[1];
  RSBaseReq *baseReq;
} RSGetAllContactReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseReq",
        .dataTypeSpecific.className = GPBStringifySymbol(RSBaseReq),
        .number = RSGetAllContactReq_FieldNumber_BaseReq,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RSGetAllContactReq__storage_, baseReq),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RSGetAllContactReq class]
                                     rootClass:[RSSpbasecgiRoot class]
                                          file:RSSpbasecgiRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RSGetAllContactReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001G\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RSGetAllContactResp

@implementation RSGetAllContactResp

@dynamic hasBaseResp, baseResp;
@dynamic contactArray, contactArray_Count;

typedef struct RSGetAllContactResp__storage_ {
  uint32_t _has_storage_[1];
  RSBaseResp *baseResp;
  NSMutableArray *contactArray;
} RSGetAllContactResp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseResp",
        .dataTypeSpecific.className = GPBStringifySymbol(RSBaseResp),
        .number = RSGetAllContactResp_FieldNumber_BaseResp,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RSGetAllContactResp__storage_, baseResp),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "contactArray",
        .dataTypeSpecific.className = GPBStringifySymbol(RSContact),
        .number = RSGetAllContactResp_FieldNumber_ContactArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(RSGetAllContactResp__storage_, contactArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RSGetAllContactResp class]
                                     rootClass:[RSSpbasecgiRoot class]
                                          file:RSSpbasecgiRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RSGetAllContactResp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001H\000\002\000Contact\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
