// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spcgi.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class RSBaseReq;
@class RSBaseResp;
@class RSMsg;
@class RSProfile;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - RSSpcgiRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface RSSpcgiRoot : GPBRootObject
@end

#pragma mark - RSLoginReq

typedef GPB_ENUM(RSLoginReq_FieldNumber) {
  RSLoginReq_FieldNumber_BaseReq = 1,
  RSLoginReq_FieldNumber_Code = 2,
};

@interface RSLoginReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, copy, null_resettable) NSString *code;
/** Test to see if @c code has been set. */
@property(nonatomic, readwrite) BOOL hasCode;

@end

#pragma mark - RSLoginResp

typedef GPB_ENUM(RSLoginResp_FieldNumber) {
  RSLoginResp_FieldNumber_BaseResp = 1,
  RSLoginResp_FieldNumber_OpCode = 2,
  RSLoginResp_FieldNumber_UserName = 3,
  RSLoginResp_FieldNumber_SessionKey = 4,
  RSLoginResp_FieldNumber_Profile = 5,
};

@interface RSLoginResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite) uint32_t opCode;

@property(nonatomic, readwrite) BOOL hasOpCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

@property(nonatomic, readwrite, copy, null_resettable) NSData *sessionKey;
/** Test to see if @c sessionKey has been set. */
@property(nonatomic, readwrite) BOOL hasSessionKey;

@property(nonatomic, readwrite, strong, null_resettable) RSProfile *profile;
/** Test to see if @c profile has been set. */
@property(nonatomic, readwrite) BOOL hasProfile;

@end

#pragma mark - RSUpLoadImgReq

typedef GPB_ENUM(RSUpLoadImgReq_FieldNumber) {
  RSUpLoadImgReq_FieldNumber_BaseReq = 1,
  RSUpLoadImgReq_FieldNumber_CliImgId = 2,
  RSUpLoadImgReq_FieldNumber_Total = 3,
  RSUpLoadImgReq_FieldNumber_OffSet = 4,
  RSUpLoadImgReq_FieldNumber_Buff = 5,
};

@interface RSUpLoadImgReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, copy, null_resettable) NSData *cliImgId;
/** Test to see if @c cliImgId has been set. */
@property(nonatomic, readwrite) BOOL hasCliImgId;

@property(nonatomic, readwrite) uint32_t total;

@property(nonatomic, readwrite) BOOL hasTotal;
@property(nonatomic, readwrite) uint32_t offSet;

@property(nonatomic, readwrite) BOOL hasOffSet;
@property(nonatomic, readwrite, copy, null_resettable) NSData *buff;
/** Test to see if @c buff has been set. */
@property(nonatomic, readwrite) BOOL hasBuff;

@end

#pragma mark - RSUpLoadImgResp

typedef GPB_ENUM(RSUpLoadImgResp_FieldNumber) {
  RSUpLoadImgResp_FieldNumber_BaseResp = 1,
  RSUpLoadImgResp_FieldNumber_SvrImgId = 2,
};

@interface RSUpLoadImgResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *svrImgId;
/** Test to see if @c svrImgId has been set. */
@property(nonatomic, readwrite) BOOL hasSvrImgId;

@end

#pragma mark - RSSyncReq

typedef GPB_ENUM(RSSyncReq_FieldNumber) {
  RSSyncReq_FieldNumber_BaseReq = 1,
  RSSyncReq_FieldNumber_SyncBuff = 2,
};

@interface RSSyncReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, copy, null_resettable) NSData *syncBuff;
/** Test to see if @c syncBuff has been set. */
@property(nonatomic, readwrite) BOOL hasSyncBuff;

@end

#pragma mark - RSSyncResp

typedef GPB_ENUM(RSSyncResp_FieldNumber) {
  RSSyncResp_FieldNumber_BaseResp = 1,
  RSSyncResp_FieldNumber_NextSyncBuff = 2,
  RSSyncResp_FieldNumber_MsgArray = 3,
};

@interface RSSyncResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nextSyncBuff;
/** Test to see if @c nextSyncBuff has been set. */
@property(nonatomic, readwrite) BOOL hasNextSyncBuff;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSMsg*> *msgArray;
/** The number of items in @c msgArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgArray_Count;

@end

#pragma mark - RSGetAllContactReq

typedef GPB_ENUM(RSGetAllContactReq_FieldNumber) {
  RSGetAllContactReq_FieldNumber_BaseReq = 1,
};

@interface RSGetAllContactReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@end

#pragma mark - RSGetAllContactResp

typedef GPB_ENUM(RSGetAllContactResp_FieldNumber) {
  RSGetAllContactResp_FieldNumber_BaseResp = 1,
  RSGetAllContactResp_FieldNumber_UserNameArray = 2,
};

@interface RSGetAllContactResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *userNameArray;
/** The number of items in @c userNameArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userNameArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
