// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spcgicomm.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - RSSpcgicommRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface RSSpcgicommRoot : GPBRootObject
@end

#pragma mark - RSPKG

typedef GPB_ENUM(RSPKG_FieldNumber) {
  RSPKG_FieldNumber_Str = 1,
  RSPKG_FieldNumber_Data_p = 2,
};

@interface RSPKG : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *str;
/** Test to see if @c str has been set. */
@property(nonatomic, readwrite) BOOL hasStr;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RSBaseReq

typedef GPB_ENUM(RSBaseReq_FieldNumber) {
  RSBaseReq_FieldNumber_SessionKey = 1,
  RSBaseReq_FieldNumber_Uin = 2,
  RSBaseReq_FieldNumber_DeviceId = 3,
  RSBaseReq_FieldNumber_DeviceType = 4,
  RSBaseReq_FieldNumber_ClientVersion = 5,
};

@interface RSBaseReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionKey;
/** Test to see if @c sessionKey has been set. */
@property(nonatomic, readwrite) BOOL hasSessionKey;

@property(nonatomic, readwrite) uint32_t uin;

@property(nonatomic, readwrite) BOOL hasUin;
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;
/** Test to see if @c deviceId has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceId;

/** enDeviceType */
@property(nonatomic, readwrite) uint32_t deviceType;

@property(nonatomic, readwrite) BOOL hasDeviceType;
@property(nonatomic, readwrite) uint32_t clientVersion;

@property(nonatomic, readwrite) BOOL hasClientVersion;
@end

#pragma mark - RSBaseResp

typedef GPB_ENUM(RSBaseResp_FieldNumber) {
  RSBaseResp_FieldNumber_ErrCode = 1,
  RSBaseResp_FieldNumber_ErrMsg = 2,
};

@interface RSBaseResp : GPBMessage

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite) BOOL hasErrCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;
/** Test to see if @c errMsg has been set. */
@property(nonatomic, readwrite) BOOL hasErrMsg;

@end

#pragma mark - RSProfile

typedef GPB_ENUM(RSProfile_FieldNumber) {
  RSProfile_FieldNumber_UserName = 1,
  RSProfile_FieldNumber_NickName = 2,
  RSProfile_FieldNumber_Sex = 3,
  RSProfile_FieldNumber_HeadImgURL = 4,
};

@interface RSProfile : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;
/** Test to see if @c nickName has been set. */
@property(nonatomic, readwrite) BOOL hasNickName;

/** enSex */
@property(nonatomic, readwrite) uint32_t sex;

@property(nonatomic, readwrite) BOOL hasSex;
@property(nonatomic, readwrite, copy, null_resettable) NSString *headImgURL;
/** Test to see if @c headImgURL has been set. */
@property(nonatomic, readwrite) BOOL hasHeadImgURL;

@end

#pragma mark - RSMsg

typedef GPB_ENUM(RSMsg_FieldNumber) {
  RSMsg_FieldNumber_Id_p = 1,
  RSMsg_FieldNumber_Type = 2,
  RSMsg_FieldNumber_Content = 3,
};

@interface RSMsg : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite, copy, null_resettable) NSData *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@end

#pragma mark - RSContact

typedef GPB_ENUM(RSContact_FieldNumber) {
  RSContact_FieldNumber_UserName = 1,
  RSContact_FieldNumber_NickName = 2,
  RSContact_FieldNumber_Sex = 3,
  RSContact_FieldNumber_HeadImgURL = 4,
};

@interface RSContact : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;
/** Test to see if @c nickName has been set. */
@property(nonatomic, readwrite) BOOL hasNickName;

/** enSex */
@property(nonatomic, readwrite) uint32_t sex;

@property(nonatomic, readwrite) BOOL hasSex;
@property(nonatomic, readwrite, copy, null_resettable) NSString *headImgURL;
/** Test to see if @c headImgURL has been set. */
@property(nonatomic, readwrite) BOOL hasHeadImgURL;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
