// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spcgi.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Msg;
@class Profile;
@class RSBaseReq;
@class RSBaseResp;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SpcgiRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SpcgiRoot : GPBRootObject
@end

#pragma mark - LoginReq

typedef GPB_ENUM(LoginReq_FieldNumber) {
  LoginReq_FieldNumber_BaseReq = 1,
  LoginReq_FieldNumber_Code = 2,
};

@interface LoginReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, copy, null_resettable) NSString *code;
/** Test to see if @c code has been set. */
@property(nonatomic, readwrite) BOOL hasCode;

@end

#pragma mark - LoginResp

typedef GPB_ENUM(LoginResp_FieldNumber) {
  LoginResp_FieldNumber_BaseResp = 1,
  LoginResp_FieldNumber_OpCode = 2,
  LoginResp_FieldNumber_UserName = 3,
  LoginResp_FieldNumber_SessionKey = 4,
  LoginResp_FieldNumber_Profile = 5,
};

@interface LoginResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite) uint32_t opCode;

@property(nonatomic, readwrite) BOOL hasOpCode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

@property(nonatomic, readwrite, copy, null_resettable) NSData *sessionKey;
/** Test to see if @c sessionKey has been set. */
@property(nonatomic, readwrite) BOOL hasSessionKey;

@property(nonatomic, readwrite, strong, null_resettable) Profile *profile;
/** Test to see if @c profile has been set. */
@property(nonatomic, readwrite) BOOL hasProfile;

@end

#pragma mark - UpLoadImgReq

typedef GPB_ENUM(UpLoadImgReq_FieldNumber) {
  UpLoadImgReq_FieldNumber_BaseReq = 1,
  UpLoadImgReq_FieldNumber_CliImgId = 2,
  UpLoadImgReq_FieldNumber_Total = 3,
  UpLoadImgReq_FieldNumber_OffSet = 4,
  UpLoadImgReq_FieldNumber_Buff = 5,
};

@interface UpLoadImgReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, copy, null_resettable) NSData *cliImgId;
/** Test to see if @c cliImgId has been set. */
@property(nonatomic, readwrite) BOOL hasCliImgId;

@property(nonatomic, readwrite) uint32_t total;

@property(nonatomic, readwrite) BOOL hasTotal;
@property(nonatomic, readwrite) uint32_t offSet;

@property(nonatomic, readwrite) BOOL hasOffSet;
@property(nonatomic, readwrite, copy, null_resettable) NSData *buff;
/** Test to see if @c buff has been set. */
@property(nonatomic, readwrite) BOOL hasBuff;

@end

#pragma mark - UpLoadImgResp

typedef GPB_ENUM(UpLoadImgResp_FieldNumber) {
  UpLoadImgResp_FieldNumber_BaseResp = 1,
  UpLoadImgResp_FieldNumber_SvrImgId = 2,
};

@interface UpLoadImgResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *svrImgId;
/** Test to see if @c svrImgId has been set. */
@property(nonatomic, readwrite) BOOL hasSvrImgId;

@end

#pragma mark - SyncReq

typedef GPB_ENUM(SyncReq_FieldNumber) {
  SyncReq_FieldNumber_BaseReq = 1,
  SyncReq_FieldNumber_SyncBuff = 2,
};

@interface SyncReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, copy, null_resettable) NSData *syncBuff;
/** Test to see if @c syncBuff has been set. */
@property(nonatomic, readwrite) BOOL hasSyncBuff;

@end

#pragma mark - SyncResp

typedef GPB_ENUM(SyncResp_FieldNumber) {
  SyncResp_FieldNumber_BaseResp = 1,
  SyncResp_FieldNumber_NextSyncBuff = 2,
  SyncResp_FieldNumber_MsgArray = 3,
};

@interface SyncResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, copy, null_resettable) NSData *nextSyncBuff;
/** Test to see if @c nextSyncBuff has been set. */
@property(nonatomic, readwrite) BOOL hasNextSyncBuff;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Msg*> *msgArray;
/** The number of items in @c msgArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
