// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spspacecgi.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class RSBaseReq;
@class RSBaseResp;
@class RSComment;
@class RSIdPair;
@class RSReceiver;
@class RSSpace;
@class RSStar;
@class RSStarImg;
@class RSStarVideo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - RSSpspacecgiRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface RSSpspacecgiRoot : GPBRootObject
@end

#pragma mark - RSStarImg

typedef GPB_ENUM(RSStarImg_FieldNumber) {
  RSStarImg_FieldNumber_ThumbURL = 1,
  RSStarImg_FieldNumber_ImgURL = 2,
};

@interface RSStarImg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbURL;
/** Test to see if @c thumbURL has been set. */
@property(nonatomic, readwrite) BOOL hasThumbURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imgURL;
/** Test to see if @c imgURL has been set. */
@property(nonatomic, readwrite) BOOL hasImgURL;

@end

#pragma mark - RSStarVideo

typedef GPB_ENUM(RSStarVideo_FieldNumber) {
  RSStarVideo_FieldNumber_ThumbURL = 1,
  RSStarVideo_FieldNumber_VideoURL = 2,
};

@interface RSStarVideo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbURL;
/** Test to see if @c thumbURL has been set. */
@property(nonatomic, readwrite) BOOL hasThumbURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *videoURL;
/** Test to see if @c videoURL has been set. */
@property(nonatomic, readwrite) BOOL hasVideoURL;

@end

#pragma mark - RSIdPair

typedef GPB_ENUM(RSIdPair_FieldNumber) {
  RSIdPair_FieldNumber_SvrId = 1,
  RSIdPair_FieldNumber_ClientId = 2,
};

@interface RSIdPair : GPBMessage

@property(nonatomic, readwrite) uint64_t svrId;

@property(nonatomic, readwrite) BOOL hasSvrId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;
/** Test to see if @c clientId has been set. */
@property(nonatomic, readwrite) BOOL hasClientId;

@end

#pragma mark - RSComment

typedef GPB_ENUM(RSComment_FieldNumber) {
  RSComment_FieldNumber_CommentId = 1,
  RSComment_FieldNumber_FromUser = 2,
  RSComment_FieldNumber_CreateTime = 3,
  RSComment_FieldNumber_Content = 4,
  RSComment_FieldNumber_PositionX = 5,
  RSComment_FieldNumber_PositionY = 6,
};

@interface RSComment : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSIdPair *commentId;
/** Test to see if @c commentId has been set. */
@property(nonatomic, readwrite) BOOL hasCommentId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUser;
/** Test to see if @c fromUser has been set. */
@property(nonatomic, readwrite) BOOL hasFromUser;

@property(nonatomic, readwrite) uint32_t createTime;

@property(nonatomic, readwrite) BOOL hasCreateTime;
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@property(nonatomic, readwrite) double positionX;

@property(nonatomic, readwrite) BOOL hasPositionX;
@property(nonatomic, readwrite) double positionY;

@property(nonatomic, readwrite) BOOL hasPositionY;
@end

#pragma mark - RSStar

typedef GPB_ENUM(RSStar_FieldNumber) {
  RSStar_FieldNumber_StarId = 1,
  RSStar_FieldNumber_Type = 2,
  RSStar_FieldNumber_Author = 3,
  RSStar_FieldNumber_CreateTime = 4,
  RSStar_FieldNumber_Img = 5,
  RSStar_FieldNumber_Video = 6,
  RSStar_FieldNumber_CommentListArray = 7,
};

@interface RSStar : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSIdPair *starId;
/** Test to see if @c starId has been set. */
@property(nonatomic, readwrite) BOOL hasStarId;

/** enStarType */
@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *author;
/** Test to see if @c author has been set. */
@property(nonatomic, readwrite) BOOL hasAuthor;

@property(nonatomic, readwrite) uint32_t createTime;

@property(nonatomic, readwrite) BOOL hasCreateTime;
@property(nonatomic, readwrite, strong, null_resettable) RSStarImg *img;
/** Test to see if @c img has been set. */
@property(nonatomic, readwrite) BOOL hasImg;

@property(nonatomic, readwrite, strong, null_resettable) RSStarVideo *video;
/** Test to see if @c video has been set. */
@property(nonatomic, readwrite) BOOL hasVideo;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSComment*> *commentListArray;
/** The number of items in @c commentListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger commentListArray_Count;

@end

#pragma mark - RSReceiver

typedef GPB_ENUM(RSReceiver_FieldNumber) {
  RSReceiver_FieldNumber_Type = 1,
  RSReceiver_FieldNumber_UserNameArray = 2,
};

@interface RSReceiver : GPBMessage

/** enReceiverType */
@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *userNameArray;
/** The number of items in @c userNameArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userNameArray_Count;

@end

#pragma mark - RSSpace

typedef GPB_ENUM(RSSpace_FieldNumber) {
  RSSpace_FieldNumber_SpaceId = 1,
  RSSpace_FieldNumber_Type = 2,
  RSSpace_FieldNumber_CreateTime = 3,
  RSSpace_FieldNumber_UpdateTime = 4,
  RSSpace_FieldNumber_Creator = 5,
  RSSpace_FieldNumber_Name = 6,
  RSSpace_FieldNumber_AuthorArray = 7,
  RSSpace_FieldNumber_Receiver = 8,
  RSSpace_FieldNumber_StarListArray = 9,
};

@interface RSSpace : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSIdPair *spaceId;
/** Test to see if @c spaceId has been set. */
@property(nonatomic, readwrite) BOOL hasSpaceId;

/** enSpaceType */
@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite) uint32_t createTime;

@property(nonatomic, readwrite) BOOL hasCreateTime;
@property(nonatomic, readwrite) uint32_t updateTime;

@property(nonatomic, readwrite) BOOL hasUpdateTime;
@property(nonatomic, readwrite, copy, null_resettable) NSString *creator;
/** Test to see if @c creator has been set. */
@property(nonatomic, readwrite) BOOL hasCreator;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *authorArray;
/** The number of items in @c authorArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger authorArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) RSReceiver *receiver;
/** Test to see if @c receiver has been set. */
@property(nonatomic, readwrite) BOOL hasReceiver;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSStar*> *starListArray;
/** The number of items in @c starListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger starListArray_Count;

@end

#pragma mark - RSCreateSpaceReq

typedef GPB_ENUM(RSCreateSpaceReq_FieldNumber) {
  RSCreateSpaceReq_FieldNumber_BaseReq = 1,
  RSCreateSpaceReq_FieldNumber_Space = 2,
};

@interface RSCreateSpaceReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, strong, null_resettable) RSSpace *space;
/** Test to see if @c space has been set. */
@property(nonatomic, readwrite) BOOL hasSpace;

@end

#pragma mark - RSCreateSpaceResp

typedef GPB_ENUM(RSCreateSpaceResp_FieldNumber) {
  RSCreateSpaceResp_FieldNumber_BaseResp = 1,
  RSCreateSpaceResp_FieldNumber_SpaceId = 2,
  RSCreateSpaceResp_FieldNumber_StarIdListArray = 3,
};

@interface RSCreateSpaceResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, strong, null_resettable) RSIdPair *spaceId;
/** Test to see if @c spaceId has been set. */
@property(nonatomic, readwrite) BOOL hasSpaceId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSIdPair*> *starIdListArray;
/** The number of items in @c starIdListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger starIdListArray_Count;

@end

#pragma mark - RSAddStarReq

typedef GPB_ENUM(RSAddStarReq_FieldNumber) {
  RSAddStarReq_FieldNumber_BaseReq = 1,
  RSAddStarReq_FieldNumber_SpaceId = 2,
  RSAddStarReq_FieldNumber_StarListArray = 3,
};

@interface RSAddStarReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, strong, null_resettable) RSIdPair *spaceId;
/** Test to see if @c spaceId has been set. */
@property(nonatomic, readwrite) BOOL hasSpaceId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSStar*> *starListArray;
/** The number of items in @c starListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger starListArray_Count;

@end

#pragma mark - RSAddStarResp

typedef GPB_ENUM(RSAddStarResp_FieldNumber) {
  RSAddStarResp_FieldNumber_BaseResp = 1,
  RSAddStarResp_FieldNumber_StarIdListArray = 2,
};

@interface RSAddStarResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSIdPair*> *starIdListArray;
/** The number of items in @c starIdListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger starIdListArray_Count;

@end

#pragma mark - RSAddCommentReq

typedef GPB_ENUM(RSAddCommentReq_FieldNumber) {
  RSAddCommentReq_FieldNumber_BaseReq = 1,
  RSAddCommentReq_FieldNumber_SpaceId = 2,
  RSAddCommentReq_FieldNumber_StarId = 3,
  RSAddCommentReq_FieldNumber_Comment = 4,
};

@interface RSAddCommentReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, strong, null_resettable) RSIdPair *spaceId;
/** Test to see if @c spaceId has been set. */
@property(nonatomic, readwrite) BOOL hasSpaceId;

@property(nonatomic, readwrite, strong, null_resettable) RSIdPair *starId;
/** Test to see if @c starId has been set. */
@property(nonatomic, readwrite) BOOL hasStarId;

@property(nonatomic, readwrite, strong, null_resettable) RSComment *comment;
/** Test to see if @c comment has been set. */
@property(nonatomic, readwrite) BOOL hasComment;

@end

#pragma mark - RSAddCommentResp

typedef GPB_ENUM(RSAddCommentResp_FieldNumber) {
  RSAddCommentResp_FieldNumber_BaseResp = 1,
  RSAddCommentResp_FieldNumber_CommentId = 2,
};

@interface RSAddCommentResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, strong, null_resettable) RSIdPair *commentId;
/** Test to see if @c commentId has been set. */
@property(nonatomic, readwrite) BOOL hasCommentId;

@end

#pragma mark - RSAddAuthorReq

typedef GPB_ENUM(RSAddAuthorReq_FieldNumber) {
  RSAddAuthorReq_FieldNumber_BaseReq = 1,
  RSAddAuthorReq_FieldNumber_SpaceId = 2,
  RSAddAuthorReq_FieldNumber_AuthorArray = 3,
};

@interface RSAddAuthorReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, strong, null_resettable) RSIdPair *spaceId;
/** Test to see if @c spaceId has been set. */
@property(nonatomic, readwrite) BOOL hasSpaceId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *authorArray;
/** The number of items in @c authorArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger authorArray_Count;

@end

#pragma mark - RSAddAuthorResp

typedef GPB_ENUM(RSAddAuthorResp_FieldNumber) {
  RSAddAuthorResp_FieldNumber_BaseResp = 1,
};

@interface RSAddAuthorResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@end

#pragma mark - RSGetAllSpaceReq

typedef GPB_ENUM(RSGetAllSpaceReq_FieldNumber) {
  RSGetAllSpaceReq_FieldNumber_BaseReq = 1,
};

@interface RSGetAllSpaceReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@end

#pragma mark - RSGetAllSpaceResp

typedef GPB_ENUM(RSGetAllSpaceResp_FieldNumber) {
  RSGetAllSpaceResp_FieldNumber_BaseResp = 1,
  RSGetAllSpaceResp_FieldNumber_ListArray = 2,
};

@interface RSGetAllSpaceResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSSpace*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - RSGetAllMySpaceReq

typedef GPB_ENUM(RSGetAllMySpaceReq_FieldNumber) {
  RSGetAllMySpaceReq_FieldNumber_BaseReq = 1,
};

@interface RSGetAllMySpaceReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@end

#pragma mark - RSGetAllMySpaceResp

typedef GPB_ENUM(RSGetAllMySpaceResp_FieldNumber) {
  RSGetAllMySpaceResp_FieldNumber_BaseResp = 1,
  RSGetAllMySpaceResp_FieldNumber_ListArray = 2,
};

@interface RSGetAllMySpaceResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSSpace*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - RSGetAllMemoirReq

typedef GPB_ENUM(RSGetAllMemoirReq_FieldNumber) {
  RSGetAllMemoirReq_FieldNumber_BaseReq = 1,
};

@interface RSGetAllMemoirReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@end

#pragma mark - RSGetAllMemoirResp

typedef GPB_ENUM(RSGetAllMemoirResp_FieldNumber) {
  RSGetAllMemoirResp_FieldNumber_BaseResp = 1,
  RSGetAllMemoirResp_FieldNumber_ListArray = 2,
};

@interface RSGetAllMemoirResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSSpace*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - RSAddMemoirReq

typedef GPB_ENUM(RSAddMemoirReq_FieldNumber) {
  RSAddMemoirReq_FieldNumber_BaseReq = 1,
  RSAddMemoirReq_FieldNumber_SpaceId = 2,
};

@interface RSAddMemoirReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, strong, null_resettable) RSIdPair *spaceId;
/** Test to see if @c spaceId has been set. */
@property(nonatomic, readwrite) BOOL hasSpaceId;

@end

#pragma mark - RSAddMemoirResp

typedef GPB_ENUM(RSAddMemoirResp_FieldNumber) {
  RSAddMemoirResp_FieldNumber_BaseResp = 1,
};

@interface RSAddMemoirResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
