// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spstorycgi.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class RSBaseReq;
@class RSBaseResp;
@class RSStory;
@class RSStoryImg;
@class RSStoryItem;
@class RSStoryToItem;
@class RSStoryVideo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum RSenStoryType

typedef GPB_ENUM(RSenStoryType) {
  RSenStoryType_StoryTypePrivate = 1,
  RSenStoryType_StoryTypePublic = 2,
};

GPBEnumDescriptor *RSenStoryType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL RSenStoryType_IsValidValue(int32_t value);

#pragma mark - Enum RSenStoryItemType

typedef GPB_ENUM(RSenStoryItemType) {
  RSenStoryItemType_StoryItemTypeText = 1,
  RSenStoryItemType_StoryItemTypeImg = 2,
  RSenStoryItemType_StoryItemTypeVideo = 3,
};

GPBEnumDescriptor *RSenStoryItemType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL RSenStoryItemType_IsValidValue(int32_t value);

#pragma mark - Enum RSenStoryToType

typedef GPB_ENUM(RSenStoryToType) {
  RSenStoryToType_StoryToTypeUser = 1,
  RSenStoryToType_StoryToTypeGroup = 2,
};

GPBEnumDescriptor *RSenStoryToType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL RSenStoryToType_IsValidValue(int32_t value);

#pragma mark - RSSpstorycgiRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface RSSpstorycgiRoot : GPBRootObject
@end

#pragma mark - RSStoryImg

typedef GPB_ENUM(RSStoryImg_FieldNumber) {
  RSStoryImg_FieldNumber_ThumbURL = 1,
  RSStoryImg_FieldNumber_ImgRl = 2,
  RSStoryImg_FieldNumber_TextArray = 3,
};

@interface RSStoryImg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbURL;
/** Test to see if @c thumbURL has been set. */
@property(nonatomic, readwrite) BOOL hasThumbURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imgRl;
/** Test to see if @c imgRl has been set. */
@property(nonatomic, readwrite) BOOL hasImgRl;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *textArray;
/** The number of items in @c textArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger textArray_Count;

@end

#pragma mark - RSStoryVideo

typedef GPB_ENUM(RSStoryVideo_FieldNumber) {
  RSStoryVideo_FieldNumber_ThumbURL = 1,
  RSStoryVideo_FieldNumber_VideoURL = 2,
  RSStoryVideo_FieldNumber_TextArray = 3,
};

@interface RSStoryVideo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbURL;
/** Test to see if @c thumbURL has been set. */
@property(nonatomic, readwrite) BOOL hasThumbURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *videoURL;
/** Test to see if @c videoURL has been set. */
@property(nonatomic, readwrite) BOOL hasVideoURL;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *textArray;
/** The number of items in @c textArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger textArray_Count;

@end

#pragma mark - RSStoryItem

typedef GPB_ENUM(RSStoryItem_FieldNumber) {
  RSStoryItem_FieldNumber_Type = 1,
  RSStoryItem_FieldNumber_FromUserName = 2,
  RSStoryItem_FieldNumber_CreateTime = 3,
  RSStoryItem_FieldNumber_Text = 4,
  RSStoryItem_FieldNumber_Img = 5,
  RSStoryItem_FieldNumber_Video = 6,
};

@interface RSStoryItem : GPBMessage

/** enStoryItemType */
@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserName;
/** Test to see if @c fromUserName has been set. */
@property(nonatomic, readwrite) BOOL hasFromUserName;

@property(nonatomic, readwrite) uint32_t createTime;

@property(nonatomic, readwrite) BOOL hasCreateTime;
@property(nonatomic, readwrite, copy, null_resettable) NSString *text;
/** Test to see if @c text has been set. */
@property(nonatomic, readwrite) BOOL hasText;

@property(nonatomic, readwrite, strong, null_resettable) RSStoryImg *img;
/** Test to see if @c img has been set. */
@property(nonatomic, readwrite) BOOL hasImg;

@property(nonatomic, readwrite, strong, null_resettable) RSStoryVideo *video;
/** Test to see if @c video has been set. */
@property(nonatomic, readwrite) BOOL hasVideo;

@end

#pragma mark - RSStoryToItem

typedef GPB_ENUM(RSStoryToItem_FieldNumber) {
  RSStoryToItem_FieldNumber_Type = 1,
  RSStoryToItem_FieldNumber_ToUserNameArray = 2,
  RSStoryToItem_FieldNumber_GroupId = 3,
};

@interface RSStoryToItem : GPBMessage

/** enStoryToType */
@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *toUserNameArray;
/** The number of items in @c toUserNameArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger toUserNameArray_Count;

@property(nonatomic, readwrite) uint32_t groupId;

@property(nonatomic, readwrite) BOOL hasGroupId;
@end

#pragma mark - RSStory

typedef GPB_ENUM(RSStory_FieldNumber) {
  RSStory_FieldNumber_Type = 1,
  RSStory_FieldNumber_ClientId = 2,
  RSStory_FieldNumber_SvrId = 3,
  RSStory_FieldNumber_CreateTime = 4,
  RSStory_FieldNumber_UpdateTime = 5,
  RSStory_FieldNumber_MemberNum = 6,
  RSStory_FieldNumber_To = 7,
  RSStory_FieldNumber_ItemArray = 8,
};

@interface RSStory : GPBMessage

/** enStoryType */
@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;
/** Test to see if @c clientId has been set. */
@property(nonatomic, readwrite) BOOL hasClientId;

@property(nonatomic, readwrite) uint64_t svrId;

@property(nonatomic, readwrite) BOOL hasSvrId;
@property(nonatomic, readwrite) uint32_t createTime;

@property(nonatomic, readwrite) BOOL hasCreateTime;
@property(nonatomic, readwrite) uint32_t updateTime;

@property(nonatomic, readwrite) BOOL hasUpdateTime;
@property(nonatomic, readwrite) uint32_t memberNum;

@property(nonatomic, readwrite) BOOL hasMemberNum;
@property(nonatomic, readwrite, strong, null_resettable) RSStoryToItem *to;
/** Test to see if @c to has been set. */
@property(nonatomic, readwrite) BOOL hasTo;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSStoryItem*> *itemArray;
/** The number of items in @c itemArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemArray_Count;

@end

#pragma mark - RSCreateStoryReq

typedef GPB_ENUM(RSCreateStoryReq_FieldNumber) {
  RSCreateStoryReq_FieldNumber_BaseReq = 1,
  RSCreateStoryReq_FieldNumber_Story = 2,
};

@interface RSCreateStoryReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, strong, null_resettable) RSStory *story;
/** Test to see if @c story has been set. */
@property(nonatomic, readwrite) BOOL hasStory;

@end

#pragma mark - RSCreateStoryResp

typedef GPB_ENUM(RSCreateStoryResp_FieldNumber) {
  RSCreateStoryResp_FieldNumber_BaseResp = 1,
  RSCreateStoryResp_FieldNumber_SvrId = 2,
};

@interface RSCreateStoryResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite) uint64_t svrId;

@property(nonatomic, readwrite) BOOL hasSvrId;
@end

#pragma mark - RSAppendStoryReq

typedef GPB_ENUM(RSAppendStoryReq_FieldNumber) {
  RSAppendStoryReq_FieldNumber_BaseReq = 1,
  RSAppendStoryReq_FieldNumber_Story = 2,
};

@interface RSAppendStoryReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

/** sub content to append */
@property(nonatomic, readwrite, strong, null_resettable) RSStory *story;
/** Test to see if @c story has been set. */
@property(nonatomic, readwrite) BOOL hasStory;

@end

#pragma mark - RSAppendStoryResp

typedef GPB_ENUM(RSAppendStoryResp_FieldNumber) {
  RSAppendStoryResp_FieldNumber_BaseResp = 1,
};

@interface RSAppendStoryResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@end

#pragma mark - RSAppendStoryToReq

typedef GPB_ENUM(RSAppendStoryToReq_FieldNumber) {
  RSAppendStoryToReq_FieldNumber_BaseReq = 1,
  RSAppendStoryToReq_FieldNumber_SvrId = 2,
  RSAppendStoryToReq_FieldNumber_To = 3,
};

@interface RSAppendStoryToReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite) uint64_t svrId;

@property(nonatomic, readwrite) BOOL hasSvrId;
@property(nonatomic, readwrite, strong, null_resettable) RSStoryToItem *to;
/** Test to see if @c to has been set. */
@property(nonatomic, readwrite) BOOL hasTo;

@end

#pragma mark - RSAppendStoryToResp

typedef GPB_ENUM(RSAppendStoryToResp_FieldNumber) {
  RSAppendStoryToResp_FieldNumber_BaseResp = 1,
};

@interface RSAppendStoryToResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@end

#pragma mark - RSGetAllStoryReq

typedef GPB_ENUM(RSGetAllStoryReq_FieldNumber) {
  RSGetAllStoryReq_FieldNumber_BaseReq = 1,
};

@interface RSGetAllStoryReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@end

#pragma mark - RSGetAllStoryResp

typedef GPB_ENUM(RSGetAllStoryResp_FieldNumber) {
  RSGetAllStoryResp_FieldNumber_BaseResp = 1,
  RSGetAllStoryResp_FieldNumber_ListArray = 2,
};

@interface RSGetAllStoryResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSStory*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - RSGetAllMyStoryReq

typedef GPB_ENUM(RSGetAllMyStoryReq_FieldNumber) {
  RSGetAllMyStoryReq_FieldNumber_BaseReq = 1,
};

@interface RSGetAllMyStoryReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@end

#pragma mark - RSGetAllMyStoryResp

typedef GPB_ENUM(RSGetAllMyStoryResp_FieldNumber) {
  RSGetAllMyStoryResp_FieldNumber_BaseResp = 1,
  RSGetAllMyStoryResp_FieldNumber_ListArray = 2,
};

@interface RSGetAllMyStoryResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSStory*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - RSGetAllMyMemoryReq

typedef GPB_ENUM(RSGetAllMyMemoryReq_FieldNumber) {
  RSGetAllMyMemoryReq_FieldNumber_BaseReq = 1,
};

@interface RSGetAllMyMemoryReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@end

#pragma mark - RSGetAllMyMemoryResp

typedef GPB_ENUM(RSGetAllMyMemoryResp_FieldNumber) {
  RSGetAllMyMemoryResp_FieldNumber_BaseResp = 1,
  RSGetAllMyMemoryResp_FieldNumber_ListArray = 2,
};

@interface RSGetAllMyMemoryResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RSStory*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - RSAddMyMemoryReq

typedef GPB_ENUM(RSAddMyMemoryReq_FieldNumber) {
  RSAddMyMemoryReq_FieldNumber_BaseReq = 1,
  RSAddMyMemoryReq_FieldNumber_SvrId = 2,
};

@interface RSAddMyMemoryReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseReq *baseReq;
/** Test to see if @c baseReq has been set. */
@property(nonatomic, readwrite) BOOL hasBaseReq;

@property(nonatomic, readwrite, copy, null_resettable) NSString *svrId;
/** Test to see if @c svrId has been set. */
@property(nonatomic, readwrite) BOOL hasSvrId;

@end

#pragma mark - RSAddMyMemoryResp

typedef GPB_ENUM(RSAddMyMemoryResp_FieldNumber) {
  RSAddMyMemoryResp_FieldNumber_BaseResp = 1,
};

@interface RSAddMyMemoryResp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RSBaseResp *baseResp;
/** Test to see if @c baseResp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseResp;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
